### ISSUE TITLE
Some questions about II2S

### ISSUE THREAD

**Issue by johannwyh** [ZPdesu/II2S#1]
First of all, thank you for presenting this marvelous work.

I have some questions to consult that,
1. Does your inverted embedding belong to W+ space? In another word, can the saved latent code be directly used as the input of a StyleGAN2 model?
2. How many iterations does it take to generate a roughly accurate reconstruction result? As 1300 iterations on 1024 resolution is sometimes too slow.
3. Is it possible to embed a batch of images at the same time?

Thank you very much!

**Comment by johannwyh** [comment]
By the way, is it possible to embed a batch of images at the same time?

**Comment by ZPdesu** [comment]
1. Yes.
2. 800 iterations are actually enough.
3. Not implemented yet... but I think it is doable.
Please check the updated code.

**Comment by jfemiani** [comment]
Good questions, seem to be answered.  I do not think this is a feature request for (3) so I will close this.
