### ISSUE TITLE
The code does not work

### ISSUE THREAD

**Issue by asmekal** [ZPdesu/II2S#2]
Hi, many thanks for releasing the code!
Unfortunately it does not work. After some debugging I figured it's stuck during PCA decomposition. And if I reduce the number of generated latents to the reasonable extent (1k-10k) there is just segmentation fault

I can see PCA's are available in the repo for main checkpoints, but I need that for my custom checkpoint

**Comment by ZPdesu** [comment]
This issue never happened to me. Not clear what's wrong there...

**Comment by jfemiani** [comment]
If you delete ffhq_PCA.npz does it recreate it?

**Comment by jfemiani** [comment]
No response, unable to reproduce.
