### ISSUE TITLE
Some questions about the pairwise distributions in W space

### ISSUE THREAD

**Issue by twinplant** [ZPdesu/II2S#3]
I'm curious how to get Fig1 in the article. After using tsne for visualization, I find that the pairwise distributions of different latent spaces are circular and.

**Comment by zhanjiahui** [comment]
Same question. 😭

**Comment by zhanjiahui** [comment]
> 

Oh, I found the answer. It is not necessary to use t-sne. Here's my code, seaborn is a convenient way to draw probability distributions.
```
import seaborn as sns

z = torch.randn(10000, 512)
G_ffhq = Generator(1024, 512, 8, channel_multiplier=2)
G_ffhq.load_state_dict(torch.load('pretrained_models/stylegan2-ffhq-config-f.pt', map_location='cpu')['g_ema'],
                       strict=True)
w = G_ffhq.get_latent(z)
w1 = w[:, 10]
w2 = w[:, 500]
w1 = w1.detach().numpy()
w2 = w2.detach().numpy()
sns.jointplot(x=w1, y=w2, kind="scatter", color="#4CB391")
plt.show()
```

**Comment by jfemiani** [comment]
Thanks for your answer, and sorry we missed this issue. Yes, I think tSNE shows you how samples cluster etc.  but it does not preserve  the shape of the distribution.
